steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'do deploying sample_http'
    args:
      - functions
      - deploy
      - sample_http
      - --trigger-http
      - --region=asia-northeast1
      - --allow-unauthenticated
      - --source=./src/sample_http
      - --runtime=python37