steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'do deploying sample_http'
    args:
      - functions
      - deploy
      - sample_http
      - --trigger-http
      - --region=asia-northeast1
      - --allow-unauthenticated
      - --source=./src/sample_http
      - --runtime=python37
      - --env-vars-file=./extras/functions_env_vars.yaml

#  - name: 'gcr.io/cloud-builders/gcloud'
#    id: 'do deploying sample'
#    args:
#      - functions
#      - deploy
#      - sample_pubsub
#      - --trriger-topic=${PUBSUB_TOPIC}
#      - --region=asia-northeast1
#      - --allow-unauthenticated
#      - --source=./src/sample_pubsub
#      - --runtime=python37
#      - --env-vars-file=./extras/functions_env_vars.yaml


#  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#    entrypoint: /bin/sh
#    args: ["./scripts/deploy-http.sh"]
#    waitFor: ["-"]
#
#  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#    entrypoint: /bin/sh
#    args: ["./scripts/deploy-pubsub.sh"]
#    waitFor: ["-"]