steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'do deploying'
    args:
      - functions
      - deploy
      - sample_http
      - --trriger-http
      - --region=asia-northeast1
      - --allow-unauthenticated
      - --source=./src/
      - --runtime=python37
      - --env-vars-file=./extras/functions_env_vars.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'do deploying'
    args:
      - functions
      - deploy
      - sample_http
      - --trriger-http
      - --region=asia-northeast1
      - --allow-unauthenticated
      - --source=./src/
      - --runtime=python37
      - --env-vars-file=./extras/functions_env_vars.yaml


#  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#    entrypoint: /bin/sh
#    args: ["./scripts/deploy-http.sh"]
#    waitFor: ["-"]
#
#  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
#    entrypoint: /bin/sh
#    args: ["./scripts/deploy-pubsub.sh"]
#    waitFor: ["-"]