steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/sh
    args: ["./scripts/deploy-http.sh"]
    waitFor: ["-"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ["./scripts/deploy-pubsub.sh"]
    waitFor: ["-"]